Repository IIoW/IIslander, pull requests merged in 2021-11, with the labels that each got.

#113 fix: prevent message preview botception
  src/modules/messagePreview/module.js
Labels: bug

#112 feat: link preview permissions
  src/modules/messagePreview/module.js
Labels: enhancement

#114 feat: firebase import & misc
  .github/CODEOWNERS
  src/constants/Blacklist.js
  src/constants/Messages.js
  src/dto/ResponseDto.js
  src/dto/UserDto.js
  src/helper/index.js
  src/helper/main.js
  src/modUtil.js
  src/modules/automod/message.js
  src/modules/leveling/awards/reactions.js
  src/modules/modCommands/commands/autoresponse.js
  src/modules/modCommands/commands/move.js
  src/util.js
  src/xpHandling.js
Labels: bug, enhancement
